adminMiddleware
SergioAndres2023/API-Hairs pull request #24
Opened 2023-06-07 18:53 UTC by SergioAndres2023

2023-06-09 11:13 UTC, carlosodero requested changes

2023-06-09 11:13 UTC, carlosodero commented on src/api/router.js
Hay que revisar bien tema admin

2023-06-09 11:13 UTC, carlosodero commented on src/middlewares/admin.middleware.js
> +    '/filter',
Revisar rutas públicas

2023-06-09 16:16 UTC, JonaTheBridge requested changes

2023-06-09 16:16 UTC, JonaTheBridge commented on src/middlewares/admin.middleware.js
> +  jwt.verify(token, 'secretWord', async (error, payload) => {
esa secretWord debería ir en .env

2023-06-09 16:16 UTC, JonaTheBridge commented on src/middlewares/admin.middleware.js
> +    '/filter',
además, no hay ninguna ruta que sea /filter o /all sin nada más

2023-06-09 16:40 UTC, JonaTheBridge requested changes

2023-06-09 16:40 UTC, JonaTheBridge commented on src/api/router.js
>  router.post('/login', auth, authController.login);
ese middleware auth debería ir en el index porque es demasiado general, todas las rutas son privadas menos dos. Y solo el middleware de admin es el que va por rutas, porque varia rutas son de admin pero otras no lo son, está bastante dividido, por eso hacemos ese middleware tan "a mano"

2023-06-13 20:54 UTC, carlosodero commented
¿Cómo va @SergioAndres2023, lo probaste? aparentemente parece ok

2023-06-14 17:19 UTC, PauloWebLogin approved these changes

2023-06-14 17:54 UTC, Sergiomll1968 approved these changes

2023-06-14 17:54 UTC, Sergiomll1968 commented on src/api/router.js
si, todas las rutas son admin. no debe ser asi, no?

2023-06-14 17:55 UTC, merged

2023-06-14 17:55 UTC, carlosodero approved these changes