Changepassword
SergioAndres2023/API-Hairs pull request #25
Opened 2023-06-09 16:13 UTC by Sergiomll1968

2023-06-09 16:24 UTC, JonaTheBridge requested changes

2023-06-09 16:24 UTC, JonaTheBridge commented on .babelrc
> +}
Hostia que bien, vais a hacer testing?

2023-06-09 16:24 UTC, JonaTheBridge commented on .eslintrc
> +    "jest": true
parece que si, me alegro mucho de esa decisión

2023-06-09 16:24 UTC, JonaTheBridge commented on package.json
> +    "test": "jest --watchAll --coverage"
nah, se confirma que vais a hacer test, te animas tú Sergio?

2023-06-09 16:24 UTC, JonaTheBridge commented on package.json
> +    "babel-jest": "^29.5.0",
más ironía sobre que vais a hacer test pero ya no se me ocurre qué poner

2023-06-09 16:24 UTC, JonaTheBridge commented on package.json
> +    "jest": "^29.5.0",
"más ironía sobre que vais a hacer test pero ya no se me ocurre qué poner" parte 2

2023-06-09 16:24 UTC, JonaTheBridge commented on src/api/users/changePasswordController.js
> +  // const isAuthorized = compareSync(password, user.password);
// borra los comentarios

2023-06-12 17:15 UTC, JonaTheBridge requested changes

2023-06-12 17:15 UTC, JonaTheBridge commented on index.js
> +import auth from './src/middlewares/auth.middleware.js';
esto es tarea de authMiddleware, no de changePassword. Quita esto del PR

2023-06-12 17:15 UTC, JonaTheBridge commented on src/api/bookings/bookings.router.js
> +router.patch('/archive/:id', bookingsController.archive); // Only permitted to admin
aqui intentas colarme un fix en un desarrollo, debería ir en un PR distinto

2023-06-12 17:15 UTC, JonaTheBridge commented on src/api/router.js
> -import auth from '../middlewares/auth.middleware.js';
todos estos fixes no son trabajo tuyo, no van en este PR, tiene que solucionarlo otra persona

2023-06-12 17:15 UTC, JonaTheBridge commented on src/api/users/users.controller.js
> +  // const { token } = req.headers.authorization;
linea comentada

2023-06-12 17:15 UTC, JonaTheBridge commented on src/api/users/users.controller.js
> +  if (!token || !password) {
en el body no te llega una password y una password repetida??? porque deberías comprobar si son iguales o no

2023-06-12 17:15 UTC, JonaTheBridge commented on src/api/users/users.service.js
> +    from: 'Los máquinas de TheBridge <correothebridge01@gmail.com',
aqui no cierras el >

2023-06-12 17:15 UTC, JonaTheBridge commented on src/api/users/users.service.js
> +      const myError = { status: 403, message: 'Authentication failed' };
ese mensaje de error no me gusta mucho, nos costaría mucho identificar que es error de token

2023-06-12 17:15 UTC, JonaTheBridge commented on src/middlewares/auth.middleware.js
>      '/filter',
todo esto no es tarea de este PR, es tema de middleware. Debería hacerlo otra persona

2023-06-12 18:00 UTC, JonaTheBridge requested changes

2023-06-12 18:00 UTC, JonaTheBridge commented on src/api/users/users.controller.js
> +  if (email === '') {
if (!email) {....

2023-06-12 18:00 UTC, JonaTheBridge commented on src/api/users/users.controller.js
> +  if (!(password === repeatedPassword)) {
password !== repeatedPassword

2023-06-12 18:00 UTC, JonaTheBridge commented on src/api/users/users.service.js
> +import nm from 'nodemailer';
menudo pro, nm... oh la la

2023-06-12 18:00 UTC, JonaTheBridge commented on src/api/users/users.service.js
> +dotenv.config();
???

Esto no va aqui ni de coña

2023-06-12 18:00 UTC, JonaTheBridge commented on src/api/users/users.service.js
> +  let email;
1)

2023-06-12 18:00 UTC, JonaTheBridge commented on src/api/users/users.service.js
> +    email = payload.email;
2)

Por que no return payload.email???

2023-06-12 18:00 UTC, JonaTheBridge commented on src/api/users/users.service.js
> +  return email;
3)

2023-06-12 18:05 UTC, Sergiomll1968 commented on src/api/users/users.service.js
> +  let email;
?

2023-06-12 18:18 UTC, JonaTheBridge approved these changes

2023-06-12 18:40 UTC, PauloWebLogin approved these changes

2023-06-12 21:11 UTC, SergioAndres2023 approved these changes

2023-06-13 20:49 UTC, carlosodero approved these changes

2023-06-14 17:18 UTC, merged