process
SergioAndres2023/API-Hairs pull request #26
Opened 2023-06-09 16:26 UTC by PauloWebLogin

2023-06-09 16:44 UTC, JonaTheBridge requested changes

2023-06-09 16:44 UTC, JonaTheBridge commented on babelrc.js
> +{
este archivo es para testing, si lo pones es porque vas a hacer testing?

2023-06-09 16:44 UTC, JonaTheBridge commented on package.json
> +    "test": "jest --watchAll --coverage"
este script es para testing, si lo pones es porque vas a hacer testing?

2023-06-09 16:44 UTC, JonaTheBridge commented on package.json
> +    "jest": "^29.5.0",
esta dependencia es para testing, si lo pones es porque vas a hacer testing?

2023-06-09 16:44 UTC, JonaTheBridge commented on package.json
> +    "babel-jest": "^29.5.0",
estas dependencias son para testing, si las pones es porque vas a hacer testing?

2023-06-09 16:44 UTC, JonaTheBridge commented on package.json
> +    "test": "^3.3.0"
que es esto? xD

2023-06-09 16:44 UTC, JonaTheBridge commented on src/api/adwars/awards.controller.js
tio, has vuelto a renombrar mal los ficheros??? estás cambiando awards por adwars no?

2023-06-09 16:44 UTC, JonaTheBridge commented on src/api/adwars/awards.model.js
tio, has vuelto a renombrar mal los ficheros??? estás cambiando awards por adwars no?

2023-06-09 16:44 UTC, JonaTheBridge commented on src/api/adwars/awards.repository.js
tio, has vuelto a renombrar mal los ficheros??? estás cambiando awards por adwars no?

2023-06-09 18:01 UTC, JonaTheBridge requested changes

2023-06-09 18:01 UTC, JonaTheBridge commented on package.json
> -    "nodemailer": "^6.9.3"
ahora te estás cargando esta dependencia que no es tuya : S puede joder a un compañero

2023-06-09 18:01 UTC, JonaTheBridge commented on src/api/awards/awards.router.js
> -router.patch('/update/:id', awardsController.update);
me estás mezclando dos PRs en uno. Debería ser un PR para las variables de entorno y otro para renombrar la ruta /update

2023-06-09 18:01 UTC, JonaTheBridge commented on src/api/awards/awards.router.js
> -router.patch('/update/:id', awardsController.update);
además, como el nombre del PR no es descriptivo, no se que parte de las dos sobra

2023-06-09 18:22 UTC, JonaTheBridge approved these changes

2023-06-09 18:23 UTC, SergioAndres2023 approved these changes

2023-06-10 06:51 UTC, Sergiomll1968 approved these changes

2023-06-13 20:43 UTC, carlosodero requested changes

2023-06-13 20:43 UTC, carlosodero commented on .env
@PauloWebLogin no puedes subir el .env
tienes que ejecutar en tu rama (process) **git rm --cached .env**  para volver a commitear y pushear a tu rama (process)

2023-06-13 20:46 UTC, carlosodero requested changes

2023-06-13 20:46 UTC, carlosodero commented on src/api/auth/auth.service.js
> +  const token = jwt.sign(payload, AUTH_SECRET_KEY, {
AUTH_SECRET_KEY lo tenemos definido como **JWT_SECRET** (ver slack)

2023-06-13 20:46 UTC, carlosodero commented on src/api/auth/auth.service.js
> +    expiresIn: AUTH_EXPIRES_IN,
AUTH_EXPIRES_IN lo tenemos definido como **JWT_EXPIRES_IN** (ver slack)

2023-06-14 17:11 UTC, carlosodero commented
IMPLEMENTADO EN OTRO PR

2023-06-14 17:11 UTC, closed without merging