Email validation
SergioAndres2023/API-Hairs pull request #27
Opened 2023-06-09 18:12 UTC by carlosodero

2023-06-09 18:20 UTC, JonaTheBridge requested changes

2023-06-09 18:20 UTC, JonaTheBridge commented on src/api/auth/auth.service.js
> -
puede que te hayas cargado el login??

2023-06-09 18:20 UTC, JonaTheBridge commented on src/api/services/services.router.js
> +router.patch('/:id', servicesController.update);
aqui me estás colando un fix en un PR de desarrollo. Debería ir en un PR aparte

2023-06-09 18:20 UTC, JonaTheBridge commented on src/api/auth/auth.service.js
> +    await userModel.updateOne(
userModel.updateOne actua sobre la base de datos. En un service???

2023-06-09 22:48 UTC, carlosodero commented on src/api/services/services.router.js
> +router.patch('/:id', servicesController.update);
@JonaTheBridge he creado otro PR #28

2023-06-12 09:58 UTC, JonaTheBridge requested changes

2023-06-12 09:58 UTC, JonaTheBridge commented on src/api/auth/auth.service.js
> +    const emailToken = jwt.sign(
si existe la función getToken, por que generamos el token a mano en vez de usar esa función? parte 1

2023-06-12 09:58 UTC, JonaTheBridge commented on src/api/auth/auth.service.js
> -  const token = getToken({ username: dbUser.username });
si existe la función getToken, por que generamos el token a mano en vez de usar esa función? parte 2

2023-06-12 09:58 UTC, JonaTheBridge commented on src/api/users/users.repository.js
> +export async function confirm({ payload }) {
Si del payload solo queremos el mail, mejor enviar solo el mail no? otra cosa es que sacases muchos datos del payload, pero no es así. parte 2

2023-06-12 09:58 UTC, JonaTheBridge commented on src/api/auth/auth.service.js
> +    await usersRepository.confirm({ payload });
Si del payload solo queremos el mail, mejor enviar solo el mail no? otra cosa es que sacases muchos datos del payload, pero no es así. parte 1

2023-06-12 11:01 UTC, carlosodero commented on src/api/auth/auth.service.js
> +    const emailToken = jwt.sign(
porque una es para Login utilizando USERNAME y la otra es para la confirmación usando EMAIL ¿lo cambio para solo email?

2023-06-12 11:02 UTC, carlosodero commented on src/api/auth/auth.service.js
> -  const token = getToken({ username: dbUser.username });
porque una es para Login utilizando USERNAME y la otra es para la confirmación usando EMAIL

2023-06-12 11:09 UTC, carlosodero commented on src/api/users/users.repository.js
> +export async function confirm({ payload }) {
el mail lo uso en la función CONFIRM del users.repository
no es válido asi?

2023-06-12 11:09 UTC, carlosodero commented on src/api/auth/auth.service.js
> +    await usersRepository.confirm({ payload });
el mail lo uso en la función CONFIRM del users.repository
no es válido asi?

2023-06-12 18:08 UTC, JonaTheBridge requested changes

2023-06-12 18:08 UTC, JonaTheBridge commented on .env
Vale!

2023-06-12 18:08 UTC, JonaTheBridge commented on src/api/auth/auth.service.js
> +    const emailToken = getToken({ username });
mira las 5 lineas anteriores, te has comido una validación

2023-06-12 18:08 UTC, JonaTheBridge commented on src/api/auth/auth.service.js
> +    const url = `http://localhost:3001/confirm/${emailToken}`;
esta URL no me gusta que vaya a pelo en el código. Debería sacarse de variables de entorno, para que cuando subamos a un server, no ponga localhost....

2023-06-12 18:08 UTC, JonaTheBridge commented on src/api/auth/auth.service.js
> +        console.log('payload', payload);
console.log???

2023-06-12 18:08 UTC, JonaTheBridge commented on src/api/auth/auth.service.js
> +        console.log('err.message', err.message);
console.log??? si quieres mantenerlo ponlo como console.error

2023-06-12 18:08 UTC, JonaTheBridge commented on src/api/auth/auth.service.js
> +    console.error(error);
:)

2023-06-12 18:23 UTC, JonaTheBridge approved these changes

2023-06-12 18:24 UTC, Sergiomll1968 approved these changes

2023-06-12 18:25 UTC, merged