fixServicesRouter
SergioAndres2023/API-Hairs pull request #28
Opened 2023-06-09 22:47 UTC by carlosodero

2023-06-10 05:45 UTC, Sergiomll1968 reviewed
Carlos, no era que manteniamos "archive" en la ruta también? Lo del id ok

2023-06-10 05:46 UTC, Sergiomll1968 requested changes
habia puesto comentario y no "request changes"
saludos

2023-06-10 06:32 UTC, carlosodero commented
**> Carlos, no era que manteniamos "archive" en la ruta también? Lo del id ok**

joder...mira que anoche me fijé cómo estaba definido en bookings.router porque tenía dudas!!
Entonces confirmamos 
**ruta/:id** para update
**ruta/archive/:id** para delete logico?

PD => ¿cómo hacéis los comentarios que no puedo hacer reply? :)

2023-06-10 06:45 UTC, Sergiomll1968 commented
jajaja, eso es. sioo miraste bookings todavia no he subido los cambios. quizas por eso te han saltado dudas

2023-06-10 21:14 UTC, carlosodero commented
ea ya está apañao

2023-06-12 09:53 UTC, JonaTheBridge approved these changes

2023-06-12 15:28 UTC, Sergiomll1968 approved these changes

2023-06-12 15:53 UTC, PauloWebLogin approved these changes

2023-06-12 16:31 UTC, merged