create database and connection
SergioAndres2023/API-Hairs pull request #6
Opened 2023-05-29 18:22 UTC by Sergiomll1968

2023-05-29 18:27 UTC, JonaTheBridge requested changes

2023-05-29 18:27 UTC, JonaTheBridge commented on .env
> +AUTH_SECRET_KEY = "hairs_app"
esto sobra

2023-05-29 18:27 UTC, JonaTheBridge commented on .env
> +AUTH_EXPIRES_IN = "1h"
y esto también

2023-05-29 18:38 UTC, JonaTheBridge requested changes

2023-05-29 18:38 UTC, JonaTheBridge commented on database.js
> -const MONGO_URL = 'mongodb+srv://admin:admin@cluster0.bt82yzh.mongodb.net/';
comentarios que no aportan, bórralos

2023-05-29 20:50 UTC, carlosodero approved these changes
ok

2023-05-29 20:51 UTC, carlosodero approved these changes
ok

2023-05-31 15:56 UTC, JonaTheBridge approved these changes

2023-05-31 15:59 UTC, SergioAndres2023 approved these changes

2023-05-31 16:13 UTC, PauloWebLogin approved these changes

2023-05-31 16:14 UTC, merged