services postNewService
SergioAndres2023/API-Hairs pull request #7
Opened 2023-05-31 21:02 UTC by carlosodero

No dormiros cabrones

2023-06-01 17:52 UTC, Sergiomll1968 reviewed
¿puedes poner el objeto de ejemplo usado para llamar a la base de datos?  ;-)

2023-06-01 18:18 UTC, SergioAndres2023 approved these changes

2023-06-01 18:36 UTC, carlosodero commented
@Sergiomll1968 creo que te refieres a esto

  {
  "serviceName": "Corte Caballero",
  "servicePrice": 15,
  "servicePoints": 3,
  "serviceMinutes": 25
  }

2023-06-01 18:46 UTC, Sergiomll1968 approved these changes
¿puedes poner el objeto de ejemplo usado para llamar a la base de datos?  ;-)

2023-06-02 13:25 UTC, JonaTheBridge requested changes

2023-06-02 13:25 UTC, JonaTheBridge commented on src/api/services/services.model.js
> +const serviceSchema = new Schema({
Igual que el id de un servicio no se llama serviceId, sino _id, no le veo sentido a llamar a la propiedades de un servicio serviceName, por ejemplo.

Cambia los nombres por name, price, points....

2023-06-02 13:25 UTC, JonaTheBridge commented on src/api/services/services.model.js
> +  // nombre: String,
y no dejemos lineas comentadas que no tengan ninguna funcionalidad informativa

2023-06-02 16:13 UTC, JonaTheBridge approved these changes

2023-06-02 16:15 UTC, PauloWebLogin approved these changes

2023-06-02 16:15 UTC, merged